name: Code Quality

on: [push, pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    env:
      APP_ENV: dev
      DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1:5432/test_db"

    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        volumes:
          - postgres_db:/var/lib/postgresql/data
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres

    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Install dependencies
        run: composer install
      - name: Prepare symfony project
        run: |
          php bin/console doctrine:database:create --if-not-exists --env=test
          php bin/console doctrine:migrations:migrate --no-interaction --env=test
          php bin/console cache:clear --no-interaction --env=test
          php bin/console doctrine:fixtures:load --no-interaction --env=test
          php bin/console sass:build
          
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
        continue-on-error: true
      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 src
        continue-on-error: true
      - name: Run tests
        run: vendor/bin/phpunit